### ISSUE TITLE
Load_ard

### ISSUE THREAD

**Issue by nanaboamah89** [digitalearthafrica/deafrica-sandbox-notebooks#113]
I tried loading **'ga_ls8c_gm_2_annual','ga_ls8c_wofs_2_annual_summary',** with the load_ard function but I got an error. Below is the code and error encountered. 
**Code**

`
lat_range = (-6.2593, -5.8701) # Small (close fit)
lon_range = (34.9901, 35.3641)

query = {
    'x': lon_range,
    'y': lat_range,
    'group_by': 'solar_day',
    'resolution': (-30, 30),
    'align': (15, 15),
    'time': ("2018")
}

crs = mostcommon_crs(dc=dc, product='ga_ls8c_gm_2_annual', query=query)

ds_map = load_ard(dc=dc,
              products=['ga_ls8c_gm_2_annual'],
              output_crs=crs,
              **query
             )

`

**Error thrown**
`
---------------------------------------------------------------------------
UnboundLocalError                         Traceback (most recent call last)
<ipython-input-79-b356bdcf961b> in <module>
     16               products=['ga_ls8c_gm_2_annual'],
     17               output_crs=crs,
---> 18               **query
     19              )
     20 

~/dev/deafrica-sandbox-notebooks/Scripts/deafrica_datahandling.py in load_ard(dc, products, min_gooddata, pq_categories_s2, pq_categories_ls, mask_pixel_quality, ls7_slc_off, predicate, dtype, **kwargs)
    254     # If `measurements` are specified but do not include pixel quality bands,
    255     #  add these to `measurements` according to collection
--> 256     if (product_type == 'c2') or (product_type == 'fc'):
    257         print('Using pixel quality parameters for USGS Collection 2')
    258         fmask_band = 'quality_l2_aerosol'

UnboundLocalError: local variable 'product_type' referenced before assignment

`

**Comment by cbur24** [comment]
@nanaboamah89 `load_ard` doesn't handle geomedian or WOfS products. The function is designed to handle the Landsat and S2 timeseries data.  If you want to load other product you need to use `dc.load()`
