### ISSUE TITLE
RGB function evaluates dask multiple times

### ISSUE THREAD

**Issue by andrewdhicks** [digitalearthafrica/deafrica-sandbox-notebooks#141]
Passing a dask array to matplotlib functions can result in the dask array being evaluated multiple times. This happens with `robust=True`, presumably as the function internally calculates the 2 and 98 percentiles.

(PR to follow)

**Comment by robbibt** [comment]
Ah, this would be a great thing to fix. Can you tag me if you find a solution so I can copy it across to `dea-notebooks`? I suspect this will also happen with the `percentile_stretch` param too

**Comment by robbibt** [comment]
Hey @cbur24 @andrewdhicks did this ever get fixed? I'd love to update this in dea-notebooks too

**Comment by cbur24** [comment]
Yeah I merged @andrewdhicks's patch the other week, so whatever is in the master branch now is the fix
