### ISSUE TITLE
Vegetation_phenology error: ModuleNotFoundError: No module named 'deafrica_temporal_statistics'

### ISSUE THREAD

**Issue by mubea** [digitalearthafrica/deafrica-sandbox-notebooks#152]
Vegetation_phenology notebook generates a ModuleNotFoundError: No module named 'deafrica_temporal_statistics' and notebook can be viewed here https://gist.github.com/mubea/887d76f8d14fbc9f9811f057a95e0c3d   and screenshot here 
![image](https://user-images.githubusercontent.com/35444636/90114405-57061400-dd5b-11ea-97d9-2da189cc1a2a.png)  @andrewdhicks @caitlinadams @nanaboamah89

**Comment by nanaboamah89** [comment]
@mubea Where is this notebook located.

**Comment by mubea** [comment]
> @mubea Where is this notebook located.

https://drive.google.com/file/d/1xcDNwMTJzYKQPW23nkhUQLw0IEDVl8-y/view?usp=sharing

**Comment by cbur24** [comment]
@mubea @nanaboamah89 the script `deafrica_temporal_statistics.py` and the `Vegetation_phenology.ipynb` notebook is located in the `dcalphenology` branch on the repo https://github.com/digitalearthafrica/deafrica-sandbox-notebooks/tree/dcalphenology
