### ISSUE TITLE
Beginner's Guide Feedback from Lina Yeboah

### ISSUE THREAD

**Issue by andrewdhicks** [digitalearthafrica/deafrica-sandbox-notebooks#153]
Lina Yeboah, a Ghanaian student Edward is working with on the illegal mining use case has pointed out small errors/inconsistencies in the beginners guide:

- [ ] The term elements, and objects are used several times but what is the difference between the two? Are datasets objects, if they are, then what are the elements?
- [ ] Using xarrays is much easier with more functionality. But are there instances where xarrys may not be convenient and where numpy is necessary?
- [ ]  In the products and measurements notebook, in the 'Visualizing available data' section, the dropdown menu is at the top left and not the top right as is written in the guide. 
- [ ] The explanation of the task graph in the 8 tutorial (Parallel Processing with Dask); point 2 should read Circles and not rectangles 
- [ ] In the Recommended Steps section, it mentions 6 tutorials but they are actually 8. 
- [ ] Are there some additional resources you could share with me to better my understanding of the Platform and how it works? I would appreciate it if you could share them with me. 
- [ ] I would also like to know the next steps from here.

**Comment by eefaye** [comment]
I'm interested in following up with this. Will try and do so next week pending other commitments.

**Comment by eefaye** [comment]
@andrewdhicks, I would appreciate a proofread for accuracy and hope these responses can be forwarded on to Lina.

- [x] **The term elements, and objects are used several times but what is the difference between the two? Are datasets objects, if they are, then what are the elements?**
Elements and objects are not the same. 
In Python, "objects" are a data type used to structure the programming language. In the Beginner's Guide `02_Products_and_measurements`, we create an object called `dc` which refers to the datacube instance we create to connect to the Open Data Cube. The question was "are datasets objects?" Generally, yes. We load datasets as an object from the Open Data Cube.  
"Elements" are part of coding terminology (not unique to Python) used to describe bits of code. Element refers to a value or item in a list. For instance, if we had a list:
``list = [0, 1, 2, 3]``
then this list has four elements. The first element is `0` (the first item in the list) and the second element is `1`. See `06_Intro_to_numpy` for more examples. (Note in that notebook we use numpy arrays, `np.array()`. `np.array is an object, but the items inside the square brackets are the elements.)

- [x] **Using xarrays is much easier with more functionality. But are there instances where xarrys may not be convenient and where numpy is necessary?**
Not often, as `xarray` retains metadata and is much more useful when working with Earth observation data in the Sandbox. 

- [x] **In the products and measurements notebook, in the 'Visualizing available data' section, the dropdown menu is at the top left and not the top right as is written in the guide.**
Thank you, this has been fixed.

- [x] **The explanation of the task graph in the 8 tutorial (Parallel Processing with Dask); point 2 should read Circles and not rectangles**
Point 1 and 2 are actually referring to the rectangles at the very bottom of the task graph (they are empty), not the circles. The circles hold the "load commands" referred to in Point 2.

- [x] **In the Recommended Steps section, it mentions 6 tutorials but they are actually 8.**
Thank you, this has been fixed.

- [x] **Are there some additional resources you could share with me to better my understanding of the Platform and how it works? I would appreciate it if you could share them with me. I would also like to know the next steps from here.**
Check out [Real world examples](https://github.com/digitalearthafrica/deafrica-sandbox-notebooks/tree/master/Real_world_examples) to see how the Sandbox can be used to solve current issues. We recommend modifying the code to try your own area and time of interest.

**Comment by andrewdhicks** [comment]
This looks really good. Thanks @eefaye! Edward should be able to pass the feedback along to Lina.
