### ISSUE TITLE
Split and update dataset notebooks

### ISSUE THREAD

**Issue by fangfy** [digitalearthafrica/deafrica-sandbox-notebooks#190]
For each DE Africa Dataset notebook: split into one no code technical description and one ODC how to notebook. Design for docs building.

**Comment by eefaye** [comment]
Datasets - Technical specs now live in the docs repo, https://github.com/digitalearthafrica/deafrica-docs and will be compiled into the docs website.
See PR 1 on that repo for additional folder structure (data_specs and _static/data_specs)

Datasets - load and use guides are staying in this repo in the Datasets folder. @cbur24 currently helping to update.
