### ISSUE TITLE
OTPS Tidal Models not available in Cape Town sandboxes

### ISSUE THREAD

**Issue by eefaye** [digitalearthafrica/deafrica-sandbox-notebooks#214]
**Issue**
Notebooks calling upon `tidal_tag` from `deafrica_tools.coastal` in the Cape Town dev and prod sandboxes fail due to the error:

```
Using user-supplied tide modelling location: -15.99, 11.74

b"At line 114 of file predict_tide.f90 (unit = 1)\nFortran runtime error: Cannot open file '/var/share/TPX08_atlas_compact/Model_atlas': No such file or directory\n\nError termination. Backtrace:\n#0  0x43acda\n#1  0x43aed5\n#2  0x43b69d\n#3  0x43d09d\n#4  0x43d3e4\n#5  0x403d28\n#6  0x4137a5\n#7  0x4c5288\n#8  0x401059"

An exception has occurred, use %tb to see the full traceback.

SystemExit: 1

```

Importing the required packages does not raise any errors in Cape Town:
```
from otps import TimePoint
from otps import predict_tide
```

However, the notebooks run without issue in Oregon.

**Steps to recreate:**
1. Log into a Cape Town sandbox
2. Open `Real world examples/Mangrove analysis`
3. Run the notebook

*Note the other tidal notebooks require full Landsat archive, which is currently unavailable. Only the Mangrove notebook uses S-2.*

**Comment by cbur24** [comment]
@NikitaGandhi resolved this issue
