### ISSUE TITLE
RasterioIOError: Read or write failed - Water Extent notebook

### ISSUE THREAD

**Issue by mubea** [digitalearthafrica/deafrica-sandbox-notebooks#215]
RasterioIOError: Read or write failed. /vsis3/deafrica-data/usgs/c1/l8/166/61/2017/08/24/LC08_L1TP_166061_20170824_20170913_01_T1_sr_band2.tif, band 1: IReadBlock failed at X offset 10, Y offset 14: TIFFReadEncodedTile() failed see more information here: https://gist.github.com/mubea/318847aa49539657031258b030db4311. and notebook file here: https://drive.google.com/file/d/1CKpSZvmhv7BQvOnu1UXKP_OhS-kqfHKo/view?usp=sharing

@cbur24 @nanaboamah89 

# Define the area of interest
lat = -2.4144
lon = 40.6744

lat_buffer = 0.0129
lon_buffer = 0.0189

# Combine central lat,lon with buffer to get area of interest
lat_range = (lat - lat_buffer, lat + lat_buffer)
lon_range = (lon - lon_buffer, lon + lon_buffer)

# Define the start year and end year
start_year = '2013'
end_year = '2019'

# Define the threshold
threshold_value = 0.75

**Comment by eefaye** [comment]
According to @Kirill888  this may be fixed by upgrading GDAL and Python, we are on 3.0.4 and current release is 3.3.1. It could also be a symptom of networking errors, these errors occurred in much greater frequency when S3 end point was routed via Internet (but that mis-configuration was since fixed).

**Comment by eefaye** [comment]
@mubea This is solved by adding `skip_broken_datasets=True` into both load statements. Thanks @Kirill888 

```
#Create a query object
query = {
    'x': lon_range,
    'y': lat_range,
    'resolution': (-30, 30),
    'output_crs':'EPSG:6933',
    'time': (start_year, end_year),
    'dask_chunks':{'time':1,'x':1000,'y':1000}
}

#load landsat 8 data
ds_landsat = load_ard(dc=dc,
                     products=['ls8_usgs_sr_scene'],
                     measurements=['red', 'green', 'blue'],
                     min_gooddata=0.75,
                     group_by='solar_day',
                     skip_broken_datasets=True,
                     **query)

# Load WOfS
ds = dc.load(product=["ga_ls8c_wofs_2"],
             fuse_func=wofs_fuser,
             group_by='solar_day',
             skip_broken_datasets=True,
             **query
            )

print(ds_landsat)
```
