### ISSUE TITLE
Use Case: Analyzing Effects of the Drought on Inundation Extent and Vegetation Cover Dynamics

### ISSUE THREAD

**Issue by nanaboamah89** [digitalearthafrica/deafrica-sandbox-notebooks#216]
**Title:** 

Analyzing Effects of the 2019 Drought on Inundation Extent and Vegetation Cover Dynamics in the Okavango Delta 

**Aim:**

To assess the effect of 2019 drought on inundation extent and vegetation cover types in the Okavango Delta: with main emphasis on floodplain vegetation, riparian woodland, and dryland vegetation. 
The results of the use case will contribute to development of large-scale low inundation extent map products and provide recent baseline maps on vegetation cover types of dynamics in the Okavango Delta system at a landscape approach, which are essential elements for integrated wetland and climate risks management by relevant decision makers.  

**Study area:**

![Picture1](https://user-images.githubusercontent.com/9433467/117004838-1037c000-acd6-11eb-8fe9-557c49376bd0.png)

**Input data:**

-  Okavango delta Vector file
-  Sentinel Data: May - September 2019
-  Water Observation from Space: May - September 2019

**Expected outcomes and outputs:**

- The 2019 low flood extent Map (May to September).  This will provide a basis for high spatial resolution Earth Observation Derived information on the effects of drought stress in the Okavango Delta wetland water extent, which is essential for improved environmental and climate risks management by decision makers
- land cover classification for water, aquatic vegetation, primary floodplains, secondary floodplains, grassland, riparian vegetation, dry grassland/saltpan, dry woodland. May to September or extend to Apr - Oct/Nov.

**Additional information: **

McCarthy, J. Gumbricht, T. & McCarthy, T.S. (2005). Ecoregion classification in the Okavango Delta, Botswana from multitemporal remote sensing.  International Journal of Remote Sensing 26 (19): 4339–4357.

**Comment by fangfy** [comment]
If fine details are desired, suggest use Sentinel-2 only. See e.g. GeoMAD compared to WOfS: http://maps.digitalearth.africa/#share=s-wAYSHvzW1S6w9JXNfhOSY3QhR2G

**Comment by kmfundisi** [comment]
Fine details are required  as per the article by McCarthy et al 2005. We are using McCarthy et al as a reference for our landcover types.  Floodplain vegetation could be one class for simplicity. But since we are interested in the effect of drought on water and vegetation cover, it would be interesting to separate the primary from secondary floodplains.
i.e. Water, aquatic vegetation, primary floodplains, secondary floodplains, grassland, riparian vegetation, dry grassland/saltpan, dry woodland

**Comment by kmfundisi** [comment]
The Okavango Delta inundation extent peaks in May when water reaches its outlets (We are now experiencing peak inundation in Thamalakane River and Kunyere/Lake Ngami  for the past 2 weeks.
The inundation will remain high until September at the end of our Winter/Dry season ( May-August)

**Comment by kmfundisi** [comment]
We could still explore both methods NDWI- WOfS for  inundation extent and image classification for landcover types after setting a baseline year so that we can apply  image differencing/change detection.

**Comment by fangfy** [comment]
thanks @kmfundisi. So the desired outcomes:
1. inundation extent for May to September 2019
2. land cover classification for water, aquatic vegetation, primary floodplains, secondary floodplains, grassland, riparian vegetation, dry grassland/saltpan, dry woodland. This could be May to September or for a more extended period from May?

**Comment by fangfy** [comment]
Also, are there reference land cover data available? to train or constrain land cover classification?

**Comment by kmfundisi** [comment]
@fangfy  it could be extended from April-October/November, our rainy season start around October/November until March
The reason for choosing a dry season is to avoid cloud noise, and capture the wetland properly.

**Comment by kmfundisi** [comment]
The standardized landcover data for  trans-boundary river basins in Southern Africa is under development in our GMES & Africa  Project using Landsat data.
At the moment there is no standardized landcover for Okavango Delta

**Comment by kmfundisi** [comment]
We can set the timeline together

**Comment by fangfy** [comment]
> We can set the timeline together

Let's aim to get a project plan together including timeline in the next 1-2 weeks if that works.

**Comment by kmfundisi** [comment]
It is fine, we can work on the project plan together for the next two weeks.

**Comment by fangfy** [comment]
hey @kmfundisi, what about:
This week, I'll start a branch and a notebook and pick an area to do some quick water mapping using S2 and WOfS.
I'll share the notebook so you can have a look.
We meet late next week or early the week after to talk about the water mapping and discuss requirements for the land cover maps.
