### ISSUE TITLE
Filtering of Negative Surface Reflectance for Band in load_ard function

### ISSUE THREAD

**Issue by nanaboamah89** [digitalearthafrica/deafrica-sandbox-notebooks#269]
Will it be possible to remove bands with negative surface reflectance value in the load_ard functions when datasets are being loaded to prevent into the sandbox for analysis. 

Thank you.

**Comment by cbur24** [comment]
Thanks @nanaboamah89, I have added this issue to this [project board](https://github.com/digitalearthafrica/deafrica-sandbox-notebooks/projects/2)
