### ISSUE TITLE
"CPLReleaseMuted Error=1" running crop health notebook 

### ISSUE THREAD

**Issue by rsignell-usgs** [digitalearthafrica/deafrica-sandbox-notebooks#331]
This didn't seem like a real error, but it does say "error" and is in a pink scary box.    Could be worrisome to a new user since this is the very first cell of the first notebook (the crop health notebook)?

 ![2021-12-15_8-17-52](https://user-images.githubusercontent.com/1872600/146194659-dfc20c21-0c59-4871-9ac3-74d3992aa503.png)

Perhaps something could be added to the training/notebook about this error, and perhaps something about python warnings since these often come up with library functions have been deprecated but the code that uses them hasn't been updated yet, right?

(also... this training material is AMAZING, what great work!)

**Comment by cbur24** [comment]
Thanks @rsignell-usgs, this is known issue that is a bit mysterious - every time we think we've solved it, it pops up again. It doesn't actually seem to cause any problems, just a bit scary like you say.  If we can't solve it we will document it like you suggest.

**Comment by eefaye** [comment]
https://github.com/rasterio/rasterio/issues/2117 
https://github.com/OSGeo/gdal/issues/2278
It's been raised and closed elsewhere but we haven't been able to identify a direct cause for us. Agreed it causes much alarm especially amongst users new to Python
