### ISSUE TITLE
Crop mask notebook has a broken import

### ISSUE THREAD

**Issue by alexgleith** [digitalearthafrica/deafrica-sandbox-notebooks#369]
Reported by a user.

I was working with your real-world examples on cropland extent. On the object-based filtering of pixel classifications in scalable machine learning, I encountered a module import error

![image](https://user-images.githubusercontent.com/3445853/164385262-323ec298-8e34-4e37-a78c-1d9d6b31179f.png)

**Comment by nanaboamah89** [comment]
https://github.com/digitalearthafrica/deafrica-sandbox-notebooks/blob/main/Real_world_examples/Scalable_machine_learning/5_Object-based_filtering.ipynb

**Comment by alexgleith** [comment]
Oh hey @nanaboamah89 what have you tried to fix this?
