### ISSUE TITLE
Change filmstrips notebook not working

### ISSUE THREAD

**Issue by eefaye** [digitalearthafrica/deafrica-sandbox-notebooks#373]
Real_world_examples > Change_filmstrip notebook not working for me.
![image](https://user-images.githubusercontent.com/45861242/166145817-872ad1fc-6973-4221-b1fe-0063f293137c.png)

ipyleaflet map doesn't load. If a polygon is selected it will process, but produces this error:
![image](https://user-images.githubusercontent.com/45861242/166145840-d3527444-ab4c-4999-a7f2-771467c966f8.png)

However, the exported .png is fine.

The Exporting_satellite_images notebook which also uses ipyleaflet seems to be working fine.

**Comment by fangfy** [comment]
This seems to work fine for me.
