### ISSUE TITLE
Forecasting vegetation condition notebook import error

### ISSUE THREAD

**Issue by eefaye** [digitalearthafrica/deafrica-sandbox-notebooks#374]
``import statsmodels.api as sm`` not working for me.

![image](https://user-images.githubusercontent.com/45861242/166149040-f61300f4-6171-4d20-87ce-9b4f4106bb2c.png)

**Comment by mickwelli** [comment]
The error came about when scipy updated in Feb 2022, as there is an incompatibility with new scipy and old statsmodels. Maybe we update statsmodels in the image?

**Comment by fangfy** [comment]
I believe this is fixed in the new sandbox image.
