### ISSUE TITLE
Add access to soil data

### ISSUE THREAD

**Issue by fangfy** [digitalearthafrica/deafrica-sandbox-notebooks#396]
Add a notebook example to access soil data using odc-stac: https://aws.amazon.com/marketplace/pp/prodview-3bfpv6jsl4tqk?sr=0-4&ref_=beagle&applicationId=AWSMPContessa#overview

Or it might be possible to index the dataset into ODC. @SeffatChowdhury, great if you can advise whether that is easy to do.

**Comment by SeffatChowdhury** [comment]
@fangfy According to https://www.isda-africa.com/isdasoil/isdasoil-on-aws/ the data is in COG format with STAC metadata, so indexing into ODC should be relatively straightforward.

**Comment by mickwelli** [comment]
Data now available as per pull request #441
