### ISSUE TITLE
How to convert ERA5 dataset to zarr format

### ISSUE THREAD

**Issue by fedebotu** [digitalearthafrica/deafrica-sandbox-notebooks#398]
Hi. First of all, thanks for your awesome repository!

I would like to ask, do you happen to have some code for transferring ERA5 data to the `zarr` format? I tried do it manually, but I couldn't obtain good results (slow loading / key errors / cannot rechunk). I noticed that you used a `dask` array with custom chunking, which I assume helps in fast loading times. Any help would be greatly appreciated :)

**Comment by fangfy** [comment]
> Hi. First of all, thanks for your awesome repository!
> 
> I would like to ask, do you happen to have some code for transferring ERA5 data to the `zarr` format? I tried do it manually, but I couldn't obtain good results (slow loading / key errors / cannot rechunk). I noticed that you used a `dask` array with custom chunking, which I assume helps in fast loading times. Any help would be greatly appreciated :)

We haven't done the conversion ourselves. We use the zarr format data provided by https://registry.opendata.aws/ecmwf-era5/  and it works well.

**Comment by fedebotu** [comment]
I see, thanks for your reply!
