### ISSUE TITLE
Minor update for coastlines notebook

### ISSUE THREAD

**Issue by fangfy** [digitalearthafrica/deafrica-sandbox-notebooks#407]
Link to docs page (once ready) for dataset and description. 
Update starting time to 2000.

**Comment by robbibt** [comment]
Yep, all mentions of "1988" should be changed to "2000". The "e.g. 2019" here should also be changed to "e.g. 2021":
![image](https://user-images.githubusercontent.com/17680388/196580391-a11a7933-b7a8-4a1d-9959-5a3a94effff8.png)

**Comment by gumpgourou** [comment]
Can we also change the 30'000km by 60,000km

**Comment by gumpgourou** [comment]
Also apparently ESRI is now Esri

**Comment by robbibt** [comment]
I would change "Africa has a highly dynamic, relatively unbroken, 30,000 km long coastline" to simply "Africa has a highly dynamic, over 60,000 km long coastline" without the citation for now, we can add a reference in later on if we find a good one

**Comment by fangfy** [comment]
> 
or simply start with "Africa's long and dynamic coastline is subject to a wide range of pressures, including extreme weather and climate, sea level rise and human development. "
