### ISSUE TITLE
Update Landsat Surface Reflectance notebook to include L9

### ISSUE THREAD

**Issue by lisarebelo** [digitalearthafrica/deafrica-sandbox-notebooks#428]
[https://github.com/digitalearthafrica/deafrica-sandbox-notebooks/blob/main/Datasets/Landsat_Surface_Reflectance.ipynb](url)

Under 
> Products Used 
add Landsat 9

Under
> Description
Change:
> Secondly, we will load a time series using the [load_ard()](https://github.com/digitalearthafrica/deafrica-sandbox-notebooks/blob/d576b6ef2941264e0772e09c53ade8a1f9dde8fe/Frequently_used_code/Using_load_ard.ipynb) function, which is a wrapper function around the dc.load module. This function will load all the images from Landsat 5,7 & 8, combine them, and then apply a cloud mask. The returned xarray.Dataset will contain analysis ready images with the cloudy and invalid pixels masked out.
To:
Secondly, we will load a time series using the [load_ard()](https://github.com/digitalearthafrica/deafrica-sandbox-notebooks/blob/d576b6ef2941264e0772e09c53ade8a1f9dde8fe/Frequently_used_code/Using_load_ard.ipynb) function, which is a wrapper function around the dc.load module. This function will load all the images from Landsat 5,7,8 & 9, combine them, and then apply a cloud mask. The returned xarray.Dataset will contain analysis ready images with the cloudy and invalid pixels masked out.

Change
> Using the load_ard() wrapper function to load in a concatenated, sorted, and cloud masked time series from Landsat 5, 7 & 8.
To
> Using the load_ard() wrapper function to load in a concatenated, sorted, and cloud masked time series from Landsat 5, 7, 8 & 9.

**Comment by nanaboamah89** [comment]
Landsat 9 dataset was used in the load ard and dc.load function example.

**Comment by lisarebelo** [comment]
> 

Yes - but it is not included in the description, these need updating:

Secondly, we will load a time series using the [load_ard()](https://github.com/digitalearthafrica/deafrica-sandbox-notebooks/blob/d576b6ef2941264e0772e09c53ade8a1f9dde8fe/Frequently_used_code/Using_load_ard.ipynb) function, which is a wrapper function around the dc.load module. This function will load all the images from Landsat 5,7 & 8, combine them, and then apply a cloud mask. The returned xarray.Dataset will contain analysis ready images with the cloudy and invalid pixels masked out.

Using the load_ard() wrapper function to load in a concatenated, sorted, and cloud masked time series from Landsat 5, 7 & 8.
