### ISSUE TITLE
EVI - Calculate Indices 

### ISSUE THREAD

**Issue by nanaboamah89** [digitalearthafrica/deafrica-sandbox-notebooks#448]
The formula read  as 
`(2.5 * (ds.nir - ds.red)) / (ds.nir + 6 * ds.red - 7.5 * ds. Blue + 1)` in the calculate index function. 
But the correct formula should be `2.5 * ((ds.nir - ds. Red) / (ds.nir + 6 * ds.red - 7.5 * ds. Blue + 1))`

**Comment by robbibt** [comment]
@nanaboamah89 Maths isn't my strong suite, but I _think_ both of these formulas work out the same... have you seen evidence that they produce different results?

**Comment by lisarebelo** [comment]
@robbibt they are quite different - e.g. with B, R, NIR values of 0.07, 0.2, 0.7 with the "correct" formula the EVI is 0.526316... while with the current formula the EVI is 0.862069... 

Effectively the erroneous placing of the brackets is diminishing the role of the blue band in the index (making it quite a different measure to what is intended)

**Comment by robbibt** [comment]
@lisarebelo I seem to get the same result for both formulas using those values:

`(2.5 * (0.7 - 0.2)) / (0.7 + 6 * 0.2 - 7.5 * 0.07 + 1) = 0.52631578947`

`2.5 * ((0.7 - 0.2) / (0.7 + 6 * 0.2 - 7.5 * 0.07 + 1)) = 0.52631578947`

I don't think it matters whether the `2.5` is multiplied against the entire function vs. just included in the numerator - the end result should be equivelent.

**Comment by lisarebelo** [comment]
Ok, thanks @robbibt

**Comment by mickwelli** [comment]
Thanks for raising this @nanaboamah89. I've traced the discrepancy back to the normalisation of SR values for Sentinel-2 where they are divided by 10000 when using the `calculate_indices` function. This produces different results to calculation of EVI on raw SR values which is implemented in some other packages e.g. Spyndex. I've added a demonstration in my latest push to #454
