### ISSUE TITLE
xarray ufuncs error

### ISSUE THREAD

**Issue by lisarebelo** [digitalearthafrica/deafrica-sandbox-notebooks#469]
Error calling xarray ufuncs (is it deprecated following sandbox upgrade?) Please check (radar_water_detection notebook) https://github.com/digitalearthafrica/deafrica-sandbox-notebooks/blob/main/Real_world_examples/Radar_water_detection.ipynb

**Comment by vikineema** [comment]
@lisarebelo Yes, xarray’s ufuncs have been removed, now that they can be replaced by [numpy’s ufuncs](https://numpy.org/doc/stable/reference/ufuncs.html) in all supported versions of numpy. 
![image](https://github.com/digitalearthafrica/deafrica-sandbox-notebooks/assets/39700992/1128400b-54bf-4080-953f-f4dc756d7e7c)
