### ISSUE TITLE
435.8 ERROR: Package 'deafrica-tools-2.3.2' requires a different Python: 3.8.10 not in '<3.12,>=3.9'

### ISSUE THREAD

**Issue by AimAlee** [digitalearthafrica/deafrica-sandbox-notebooks#488]
Hi everyone,

Facing the below issue please help to resolve. Thank you.

435.8 ERROR: Package 'deafrica-tools-2.3.2' requires a different Python: 3.8.10 not in '<3.12,>=3.9'
------
failed to solve: process "/bin/sh -c cd /tmp   && git clone --depth 1 https://github.com/digitalearthafrica/deafrica-sandbox-notebooks.git   && pip install deafrica-sandbox-notebooks/Tools   && rm -rf /tmp/deafrica-sandbox-notebooks" did not complete successfully: exit code: 1

**Comment by nanaboamah89** [comment]
Hi @AimAlee, I want to understand the error. Are you trying to install the packages on your system, or are you using DE Africa Sandbox, and these errors are coming up?

**Comment by AimAlee** [comment]
![Screenshot (177)](https://github.com/digitalearthafrica/deafrica-sandbox-notebooks/assets/62988681/43c5a196-eb50-4c8d-8131-4225cb6b4611)

**Comment by AimAlee** [comment]
> Hi @AimAlee, I want to understand the error. Are you trying to install the packages on your system, or are you using DE Africa Sandbox, and these errors are coming up?

Trying/following this (https://www.youtube.com/watch?v=GmqAaSX9xsk&t=58s)

**Comment by AimAlee** [comment]
> OK, @AimAlee, we would investigate that, the last time I did install the cube in the box was on Linux.

thank you for your support
