### ISSUE TITLE
Sentinel 2 loading issue - SCL Band

### ISSUE THREAD

**Issue by BrandonFeldhaus** [digitalearthafrica/deafrica-sandbox-notebooks#496]
The AWS Element 84 STAC index recently changed the Sentinel 2 data schema to no longer contain the SCL band. This results in loading errors when utilizing the load_ard function from datahandling.py because the current implementation requires the SCL band. 

Is it possible to remove the SCL band requirement from the load_ard function?

AWS Element 84 STAC Specification : https://stacindex.org/catalogs/earth-search#/43bjKKcJQfxYaT1ir3Ep6uENfjEoQrjkzhd2?t=3

![image](https://github.com/digitalearthafrica/deafrica-sandbox-notebooks/assets/59741125/b6bb9bd1-7db6-41be-9e3a-c581f6a05812)

**Comment by fangfy** [comment]
Hi @BrandonFeldhaus, I'm not aware that the SCL band is removed. I can see it in the STAC catalog. This error could mean that no data is found. Are you able to share the command that generates this error?

**Comment by BrandonFeldhaus** [comment]
I have confirmed the issue was with the casing for sentinel 2 data. I was able to modify the package locally to retrieve the band "scl" instead of "SCL" which resulted in successful loading of the data.
