### ISSUE TITLE
rgb function doesn't work well with Sentinel-1

### ISSUE THREAD

**Issue by caitlinadams** [digitalearthafrica/deafrica-sandbox-notebooks#54]
I was curious whether I could use the rgb function to make a fake 3-colour plot for Sentinel-1, using the difference between the bands as the third colour (ala [The Layman's Guide to Radar](http://ceos.org/document_management/SEO/DataCube/Laymans_SAR_Interpretation_Guide_2.0.pdf)), however, something is clearly going wrong with how it's determining the aspect ratio:

![Screen Shot 2020-03-09 at 2 57 49 pm](https://user-images.githubusercontent.com/25995927/76219677-7b8f1a80-6216-11ea-84ab-8343038eeb41.png)

**Comment by caitlinadams** [comment]
Just noticed that the [DCAL rgb  function](https://github.com/digitalearthafrica/deafrica-sandbox-notebooks/blob/master/DCAL/DCAL_utils/dc_rgb.py) seems to be working for this (see [ALOS Viewer](https://github.com/digitalearthafrica/deafrica-sandbox-notebooks/blob/master/DCAL/DCAL_notebooks/ALOS_Viewer_Version3.ipynb)), so perhaps that script can give some insight into what we need to do?

**Comment by robbibt** [comment]
Wow, yep, I'll have a look - probably something to do with the different lat/lon extents for Africa (negative and positive values on both axes)

**Comment by caitlinadams** [comment]
Thanks for fixing, @robbibt!
